#!/bin/bash

# Shamelessly stolen from https://github.com/mintsuki/dir2fat32-esp
#
# The file copy feature to seed the partition was removed.
#
# It now simply replaces the output if it exists.  No 'force' option
# is needed.  No option parsing.  Just print usage if run without
# arguments.
#
# The play-by-play output replaced with a single line showing what was
# done.  Since it's run with -e it will never get there if it fails.
#
# Uses mkfs.vfat instead of mformat.
#
# Note: while the disk image is FAT32, the partition created is
# actually of the type EFI System.  Often the type is either this or
# MS Basic Data, and probing is needed to identify it as FAT32.  This
# is an important test case as it exercises probing functionality.
#

# Create a FAT32 disk image from the contents of a directory.
#
# This tool requires the following to be available on the host system:
#
# - util-linux
# - mtools
#
# Copyright 2016 Othernet Inc, 2021 mintsuki
# Some rights reserved.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>
#

# To mount a partition, use
#   sudo kpartx -v -a image.img
#   mkdir -p tmp && sudo mount /dev/mapper/loop0p1 mnt
#
# To unmount:
#   sudo umount mnt
#   sudo kpartx -v -d image.img

set -e

usage() {
  echo "Usage: $(basename $0) OUTPUT SIZE"
  echo
  echo "Arguments:"
  echo "  OUTPUT      name of the image file"
  echo "  SIZE        size of the image in MiB (1024 based)"
  echo
  echo "NOTE: the partition created is 1MiB smaller than the container."
  echo
  echo "dir2fat32-esp"
  echo "Copyright 2016 Othernet Inc, 2021 mintsuki"
  echo "Some rights reserved."
  echo
  echo "This program is free software released under GNU GPLv3 license."
  echo "See <http://www.gnu.org/licenses/> for more information."
  echo
}

mkcontainer() {
  dd if=/dev/zero bs=1M count=0 seek=${SIZE} of="$OUTPUT" 2>/dev/null
  echo "
g
n


$(expr '(' ${SIZE} '*' 1048576 ')' / 512 - 34)
t
1
w" | fdisk "$OUTPUT" 2>/dev/null >/dev/null
}

mkpartition() {
  dd if=/dev/zero bs=1M count=0 seek=$(expr ${SIZE} - 2) of="$PARTITION" 2>/dev/null
  mkfs.vfat -F 32 -S 512 -s 4 -n "FAT32_TEST" $PARTITION
}

insertpart() {
  dd if="$PARTITION" of="$OUTPUT" bs=1M seek=1 conv=notrunc 2>/dev/null
}

# Parse remaining positional arguments
OUTPUT=${@:$OPTIND:1}
SIZE=${@:$OPTIND+1:1}

if [ -z "$OUTPUT" ] || [ -z "$SIZE" ]; then
  echo "ERROR: Missing required arguments, please see usage instructions:"
  echo
  usage
  exit 0
fi

PARTITION=${OUTPUT}.partition

rm -f $OUTPUT
mkcontainer
mkpartition
insertpart
rm -f "$PARTITION"

echo Created GPT partition on image $OUTPUT with a ${SIZE}MB FAT32 partition
